const assert=require('node:assert/strict');
const {createRun,BoundaryError}=require('../extensions/channels-assistant/runner.js');
const identity={task_id:'t1',revision:2,page:'/post/create',signature:'asset-version'};
(async()=>{
 const saved=[],run=createRun({identity,persist:async s=>saved.push(s)});let calls=0;
 assert.equal((await run.executeStep('upload',async()=>{calls++;return{preview:true};})).preview,true);
 await run.executeStep('upload',()=>calls++);assert.equal(calls,1);
 assert.equal(saved[0].steps.upload.status,'running');assert.equal(saved[1].steps.upload.status,'done');
 let release;const action=run.executeStep('cover',()=>new Promise(r=>release=r));
 while(!release)await new Promise(r=>setImmediate(r));
 await run.pause();assert.equal(run.snapshot().status,'running');release({preview:true});await action;
 assert.equal(run.snapshot().status,'paused');await assert.rejects(run.executeStep('copy',()=>{}),BoundaryError);
 await run.resume();await run.executeStep('copy',()=>({checked:true}));
 await run.pause();await run.invalidate(['copy']);await run.resume();
 await run.executeStep('copy',({previous})=>{assert.equal(previous.status,'invalidated');return{checked:true};});
 await run.finish();assert.equal(run.snapshot().status,'completed');
 const restored=createRun({identity,restored:saved[0]});assert.equal(restored.snapshot().steps.upload.status,'interrupted');
 await assert.rejects(restored.executeStep('upload',()=>{}),BoundaryError);await assert.rejects(restored.resume(),/preflight/);
 await restored.resume({identity,verified:true});await restored.executeStep('upload',({previous})=>{assert.equal(previous.status,'interrupted');return{existingPreview:true};});
 assert.throws(()=>createRun({identity:{...identity,revision:3},restored:saved[0]}),/mismatch/);
 const stopped=createRun({identity});await stopped.stop();await assert.rejects(stopped.executeStep('x',()=>{}),BoundaryError);await assert.rejects(stopped.resume(),/cannot resume/);
 let attempted=false;const broken=createRun({identity,persist:async()=>{throw new Error('disk');}});
 await assert.rejects(broken.executeStep('upload',()=>attempted=true),/disk/);assert.equal(attempted,false);
 const errors=createRun({identity});await assert.rejects(errors.executeStep('x',()=>{throw new Error('private account text');}),/private/);
 assert.equal(errors.snapshot().status,'paused');assert.equal(JSON.stringify(errors.snapshot()).includes('private'),false);
 const concurrent=createRun({identity});let done;
 const first=concurrent.executeStep('one',()=>new Promise(r=>done=r));
 await assert.rejects(concurrent.executeStep('two',()=>{}),/Another step/);
 while(!done)await new Promise(r=>setImmediate(r));await concurrent.stop();done();await first;assert.equal(concurrent.snapshot().status,'stopped');
 console.log('runner tests passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
