const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const manifest=JSON.parse(fs.readFileSync('extensions/channels-assistant/manifest.json'));
assert.deepEqual(manifest.permissions,['activeTab','storage','alarms']);
assert.equal(manifest.host_permissions.length,2);
let listener,connectListener,removedListener,updatedListener,alarmListener,activeContext=null;
const disk={};let currentDocument='doc-7',observedAccount='账号',connection={status:'bound',display_name:'账号'};const tabURL='https://channels.weixin.qq.com/platform/post/create';
const writes=[];
const context={crypto:require("node:crypto").webcrypto,setTimeout,clearTimeout,Map,Promise,AbortController,chrome:{storage:{local:{get:async key=>({[key]:disk[key]?structuredClone(disk[key]):undefined}),set:async value=>Object.assign(disk,structuredClone(value))}},alarms:{create:()=>{},onAlarm:{addListener:f=>alarmListener=f}},tabs:{get:async()=>({url:tabURL}),onRemoved:{addListener:f=>removedListener=f},onUpdated:{addListener:f=>updatedListener=f},sendMessage:async(tabId,m,options)=>{if(options?.documentId&&options.documentId!==currentDocument)throw Error('document closed');if(m.type==='observation-context')activeContext=m.payload;if(m.type==='observation-probe')return {ok:!!activeContext,...activeContext,observed_account:observedAccount};return {ok:true,observed_account:''};}},runtime:{getURL:p=>'chrome-extension://test/'+p,onConnect:{addListener:f=>connectListener=f},onMessage:{addListener:f=>listener=f}}},URL,Uint8Array,Error,String,btoa:s=>Buffer.from(s,'binary').toString('base64'),fetch:async (url,options)=>{
 if(url.endsWith('/api/channel-observations')){writes.push(JSON.parse(options.body));return {ok:true,json:async()=>({observation:{event_kind:'submit_clicked'}})};}
 if(url.endsWith('/'))return {ok:true,text:async()=>'<meta name="desk-token" content="test-token">'};
 if(url.endsWith('/api/library'))return {ok:true,json:async()=>({batches:[{id:'course',name:'课程'}],packages:{new:{batch_id:'course',sequence:1}}})};
 if(url.endsWith('/api/state'))return {ok:true,json:async()=>({accounts:[{id:'a',platform:'channels',name:'内部标签',connection},{id:'b',platform:'wechat'}],tasks:[{id:'eligible',package_id:'new',revision:1,account_id:'a',format:'video',status:'draft'},{id:'running',account_id:'a',format:'video',status:'running'},{id:'article',account_id:'b',format:'article',status:'draft'}],assets:[]})};
 return {ok:true,arrayBuffer:async()=>new Uint8Array([1,2,3]).buffer,headers:{get:()=> 'video/mp4'}};
}};
context.importScripts=path=>vm.runInContext(fs.readFileSync('extensions/channels-assistant/'+path,'utf8'),context);
vm.createContext(context);
vm.runInContext(fs.readFileSync('extensions/channels-assistant/background.js','utf8'),context);
const progressTask={id:'eligible',account_id:'a',revision:1};
const remoteProgress={account_id:'a',revision:1,status:'published',confirmed_at:'2026-10-08T10:00:00Z'};
assert.equal(context.mergePublicationProgress(progressTask,{publication_progress:remoteProgress},null).status,'published');
assert.equal(context.mergePublicationProgress({...progressTask,revision:2},{publication_progress:remoteProgress},remoteProgress),null,'old revision never hides current version');
assert.equal(context.mergePublicationProgress(progressTask,{publication_progress:remoteProgress},{...remoteProgress,status:'unconfirmed',confirmed_at:'2026-10-08T11:00:00Z'}).status,'unconfirmed','pending local undo remains visible');
assert.equal(context.mergePublicationProgress(progressTask,{publication_progress:remoteProgress},{...remoteProgress,account_id:'wrong',status:'unconfirmed'}).status,'published','other account progress cannot override');
const call=(m,s={})=>new Promise(resolve=>listener(m,s,resolve));
(async()=>{
 let r=await call({type:'state'});assert.equal(r.ok,true);assert.equal(r.result.tasks.length,1);assert.equal(r.result.tasks[0].id,'eligible');
 r=await call({type:'state'},{tab:{}});assert.equal(r.ok,false);
 r=await call({type:'state'},{tab:{id:9},url:'chrome-extension://test/popup.html?targetTab=7'});assert.equal(r.ok,true);
 r=await call({type:'state'},{tab:{id:9},url:'https://example.com/popup.html'});assert.equal(r.ok,false);
 r=await call({type:'asset',id:'a'.repeat(32)},{url:'https://example.com/'});assert.equal(r.ok,false);
 r=await call({type:'asset',id:'../bad'},{url:'https://channels.weixin.qq.com/platform'});assert.equal(r.ok,false);
 r=await call({type:'asset',id:'a'.repeat(32)},{url:'https://channels.weixin.qq.com/platform'});assert.equal(r.ok,true);assert.equal(r.result.base64,'AQID');
 function fakeFrame(frameId,counts){let callback;connectListener({name:'desk-frame',sender:{tab:{id:7},frameId,documentId:'doc-7'},onMessage:{addListener:f=>callback=f},onDisconnect:{addListener:()=>{}},postMessage:m=>queueMicrotask(()=>callback({id:m.id,ok:counts!==null,error:counts===null?'scan disconnected':undefined,result:m.op==='scan'?{path:'/micro/content/post/create',counts}:{filled:true}}))});}
 fakeFrame(0,{video:0,body:0,title:0});fakeFrame(4,{video:1,body:1,title:1});
 const top={tab:{id:7},frameId:0,documentId:'doc-7',url:'https://channels.weixin.qq.com/platform/post/create'};
 r=await call({type:'state'},top);assert.equal(r.ok,true);assert.equal(r.result.tasks[0].sequence,1);assert.equal(r.result.tasks[0].batch_id,'course');
 observedAccount='其他账号';
 r=await call({type:'observation-bind',task_id:'eligible',revision:1,binding_reason:'fill_started'},top);assert.equal(r.ok,false);assert.match(r.error,/账号不匹配/);assert.equal(activeContext,null,'wrong initial account must not receive context');
 r=await call({type:'observation-check'},top);assert.equal(r.ok,false,'wrong initial account must not persist a binding');
 observedAccount=' 账号 ';connection.display_name='账 号';
 r=await call({type:'observation-bind',task_id:'eligible',revision:1,binding_reason:'fill_started'},top);assert.equal(r.ok,true);
 observedAccount='账号';connection.display_name='账号';
 const payload={task_id:'eligible',revision:1,page_url:top.url,source:'session_observer',event_kind:'submit_clicked',event_id:'event-1'};
 r=await call({type:'observation',payload},top);assert.equal(r.ok,true);await new Promise(resolve=>setImmediate(resolve));assert.equal(writes.length,1);
 r=await call({type:'observation',payload:{...payload,task_id:'wrong'}},top);assert.equal(r.ok,false);assert.equal(writes.length,1);
 r=await call({type:'observation',payload},{...top,frameId:4,url:'https://channels.weixin.qq.com/micro/content/post/create'});assert.equal(r.ok,true);await new Promise(resolve=>setImmediate(resolve));assert.equal(writes.length,1,'same event_id is not posted twice');
 r=await call({type:'observation',payload},{...top,frameId:99});assert.equal(r.ok,false);
 r=await call({type:'observation-check'},top);assert.equal(r.ok,true);assert.equal(r.result.observed_account,'账号');
 observedAccount='其他账号';r=await call({type:'observation-check'},top);assert.equal(r.ok,false);assert.match(r.error,/账号不匹配/);
 observedAccount='';r=await call({type:'observation-check'},top);assert.equal(r.ok,true,'unknown page identity is not fabricated');
 observedAccount='其他账号';connection.status='unbound';r=await call({type:'observation-check'},top);assert.equal(r.ok,true,'unverified registry labels are not identity');
 connection={status:'bound',display_name:'ＡＩ 账号'};observedAccount='ai账号';r=await call({type:'observation-check'},top);assert.equal(r.ok,true,'NFKC whitespace and case are normalized');
 connection={status:'bound',display_name:'账号'};observedAccount='账号';
 currentDocument='different-doc';r=await call({type:'observation-check'},{...top,documentId:currentDocument});assert.equal(r.ok,false,'new document cannot inherit task binding');
 r=await call({type:'observation',payload},{...top,frameId:4});assert.equal(r.ok,false,'old subframe cannot associate with replacement top document');
 currentDocument='doc-7';
 r=await call({type:'frames'},top);assert.equal(r.result.length,2);
 r=await call({type:'field',kind:'body',op:'fill',value:'test'},top);assert.equal(r.ok,true);
 r=await call({type:'field',kind:'body',op:'fill',value:'test'},{...top,frameId:4});assert.equal(r.ok,false);
 fakeFrame(6,null);r=await call({type:'field',kind:'body',op:'fill',value:'test'},top);assert.equal(r.ok,false);assert.match(r.error,/扫描不完整/,'A valid candidate in another frame must not bypass an incomplete scan');fakeFrame(6,{video:0,body:0,title:0});
 fakeFrame(5,{video:1,body:1,title:1});r=await call({type:'field',kind:'body',op:'fill',value:'test'},top);assert.equal(r.ok,false);
 const code=fs.readFileSync('extensions/channels-assistant/content.js','utf8');assert.ok(!/exact\([^\n]*['"]发表['"]/.test(code));
 // Simulate a terminated service worker: fresh globals, same chrome.storage.local and same document.
 const restarted={...context};delete restarted.DeskDurableObservations;
 restarted.importScripts=path=>vm.runInContext(fs.readFileSync('extensions/channels-assistant/'+path,'utf8'),restarted);
 vm.createContext(restarted);vm.runInContext(fs.readFileSync('extensions/channels-assistant/background.js','utf8'),restarted);
 r=await call({type:'observation-check'},top);assert.equal(r.ok,true,'same document binding restores after worker restart');
 r=await call({type:'observation',payload:{...payload,event_id:'after-restart'}},top);assert.equal(r.ok,true);await new Promise(resolve=>setImmediate(resolve));assert.equal(writes.length,2);
 updatedListener(7,{status:'loading'});await new Promise(resolve=>setImmediate(resolve));r=await call({type:'observation-check'},top);assert.equal(r.ok,false,'navigation invalidates restored binding');
 r=await call({type:'observation-bind',task_id:'eligible',revision:1,binding_reason:'fill_started'},top);assert.equal(r.ok,true);
 removedListener(7);await new Promise(resolve=>setImmediate(resolve));r=await call({type:'observation-check'},top);assert.equal(r.ok,false,'closed tab binding removed');
 r=await call({type:'publication-confirm',task_id:'eligible',revision:1},top);assert.equal(r.ok,true);assert.equal(r.result.status,'published');
 r=await call({type:'state'},top);assert.equal(r.result.tasks[0].publication_progress.status,'published');
 r=await call({type:'publication-undo',task_id:'eligible',revision:1},top);assert.equal(r.ok,true);assert.equal(r.result.status,'unconfirmed');
 r=await call({type:'publication-confirm',task_id:'eligible',revision:999},top);assert.equal(r.ok,false);
 await new Promise(resolve=>setImmediate(resolve));
 const originalSend=context.chrome.tabs.sendMessage;let wakeups=0;
 context.chrome.tabs.sendMessage=async(tab,m,options)=>{if(m.type==='desk-frame-wakeup'){wakeups++;fakeFrame(0,{video:1,body:1,title:1});return {ok:true};}return originalSend(tab,m,options);};
 r=await call({type:'frames'},top);assert.equal(r.ok,true);assert.equal(r.result.length,1,'Frame registry recovers after worker termination');assert.equal(wakeups,1);
 r=await call({type:'frames'},top);assert.equal(wakeups,1,'A live frame connection is not restarted during an operation');
 console.log('PASS: permissions, task filtering, sender validation, asset validation and transport');
})().catch(e=>{console.error(e);process.exitCode=1});
