const assert=require('node:assert/strict');
const ux=require('../static/workspace.js');
const t=(status,mode='manual')=>({id:'t1',status,options:{mode},title:'发布标题',format:'article',body:'正文',asset_ids:[]});
assert.equal(ux.taskGroup(t('draft')),'prepare');
for(const status of ['failed','blocked'])assert.equal(ux.taskGroup(t(status)),'prepare');
for(const status of ['ready','scheduled','queued','running'])assert.equal(ux.taskGroup(t(status)),'execute');
for(const status of ['unknown','review'])assert.equal(ux.taskGroup(t(status)),'verify');
assert.equal(ux.taskGroup(t('delivered','manual')),'verify','Manual receipt is not an explicitly approved draft-only objective');
assert.equal(ux.taskStatus(t('delivered','manual')),'已记录平台草稿');
assert.equal(ux.taskGroup(t('delivered','publish')),'verify','A returned draft cannot complete a public publishing objective');
assert.equal(ux.taskGroup(t('delivered','draft')),'complete');
assert.match(ux.taskStatus(t('delivered','draft')),/本次目标/);
assert.equal(ux.taskGroup(t('published')),'complete');
assert.equal(ux.taskGroup(t('canceled')),'history');
assert.match(ux.taskStatus(t('published')),/已记录/);
assert.match(ux.taskReason({...t('draft'),body:''},{}),/缺少正文/);
assert.match(ux.taskReason({...t('draft'),format:'video',asset_ids:[]},{}),/选择一个视频/);
assert.match(ux.taskReason({...t('draft'),format:'video',asset_ids:['a']},{}),/未指定封面/);
assert.equal(ux.channelSummary([]),'尚未安排渠道');
assert.equal(ux.channelSummary([t('draft'),t('draft'),t('published'),t('canceled')]),'2 项待安排 · 1 项已完成 · 1 项已取消');
const runs=[{id:'r1',task_id:'t1',status:'unknown'},{id:'r2',task_id:'missing',status:'unknown'},{id:'r3',task_id:'t1',status:'resolved'}];
assert.deepEqual(ux.unresolvedRuns([t('draft')],runs).map(r=>r.id),['r1','r2']);
assert.deepEqual(ux.unresolvedRuns([t('unknown')],runs).map(r=>r.id),['r2']);
const normalized=ux.normalizeState({statuses:{custom:'Custom'}});
assert.equal(normalized.statuses.custom,'Custom');
assert.equal(normalized.statuses.draft,'待安排');
console.log('Workspace semantic tests passed');

assert.match(ux.taskReason({...t('draft'),format:'video',asset_ids:['a']},{assets:[]}),/素材不可用/);
assert.match(ux.taskReason({...t('draft'),format:'video',asset_ids:['a']},{assets:[{id:'a',kind:'image'}]}),/需选择视频文件/);
assert.match(ux.taskReason({...t('draft'),format:'gallery',asset_ids:['a']},{assets:[{id:'a',kind:'video'}]}),/只能选择图片/);
