let state,loading=false,lastCheck=null;
let checked=JSON.parse(localStorage.getItem("desk-checked-items")||"{}");
const targetTabId=Number(new URLSearchParams(location.search).get("targetTab"))||null;if(targetTabId)document.body.classList.add("wide");
const status=document.querySelector('#status'),select=document.querySelector('#tasks'),button=document.querySelector('#open');
async function loadState(){status.textContent='正在连接本机分发台…';button.disabled=true;try{const r=await chrome.runtime.sendMessage({type:'state'});if(!r.ok)throw Error(r.error);state=r.result;renderBatches();render();}catch(e){status.textContent=e.message;}}
loadState();
document.querySelector('#reconnect').onclick=loadState;
button.onclick=async()=>{if(loading)return;loading=true;button.disabled=true;button.textContent="正在连接视频号…";status.textContent="正在准备当前内容，请稍候。";try{
 
 const tab=targetTabId?await chrome.tabs.get(targetTabId):(await chrome.tabs.query({active:true,currentWindow:true}))[0];
 if(!tab?.url?.startsWith('https://channels.weixin.qq.com/'))throw Error('请先切换到视频号助手的发表视频页面，再打开扩展');
 const source=state.tasks.find(t=>t.id===select.value);if(source.status==='unknown'&&!confirm('这条任务结果不明。确认已检查平台，没有重复草稿或作品？'))return;
 const task={...source,options:{...source.options,collection:document.querySelector('#collection').value||source.options?.collection}};
 const start=document.querySelector('#start').value;if(start){const ordered=[...state.tasks].filter(t=>t.batch_id===document.querySelector('#batch').value&&t.status!=='unknown'&&!t.title.includes('分发流程测试')).sort(compareTasks);const index=ordered.findIndex(t=>t.id===task.id);if(index<0)throw Error('结果不明任务不能重新排期');task.assistScheduled=new Date(new Date(start).getTime()+index*3600000).toISOString();}

 if(task.asset_ids.length!==1)throw Error(task.asset_ids.length?'这条内容选中了多个视频，请在分发台保留一个要发布的视频。':'这条内容还没有选择视频，请在分发台补充视频。');
 const r=await chrome.tabs.sendMessage(tab.id,{type:'prepare',autoStart:false,task,assets:state.assets.filter(a=>task.asset_ids.includes(a.id)||a.id===task.cover_id)});
 if(!r?.ok)throw Error(r?.error||'请刷新视频号页面再试');status.textContent='辅助面板已打开；请在页面核对账号后开始。';
}catch(e){status.textContent=/Receiving end does not exist|Could not establish connection/.test(e.message)?'视频号页面尚未连接新版插件。请刷新视频号网页，再打开插件加载这条内容。':e.message;}finally{loading=false;button.disabled=!select.value;button.textContent='加载到视频号';}};

const labels={draft:'待安排',ready:'待交付',scheduled:'已排期',unknown:'需核对',blocked:'暂停',delivered:'已交付'};
function render(){if(!state)return;const q=document.querySelector('#search').value.toLowerCase(),filter=document.querySelector('#filter').value,old=select.value||localStorage.getItem("desk-selected-task");const tasks=state.tasks.filter(t=>t.batch_id===document.querySelector('#batch').value&&!t.title.includes('分发流程测试')&&(filter==='all'||!['delivered','review'].includes(t.status)&&t.publication_progress?.status!=='published')&&(!q||('第 '+String(taskOrder(t)).padStart(2,'0')+' 条 '+t.title+' '+t.account).toLowerCase().includes(q))).sort(compareTasks);select.replaceChildren(...tasks.map(t=>new Option(orderLabel(t)+' '+t.title+' · '+t.account,t.id)));if(tasks.some(t=>t.id===old))select.value=old;renderCards(tasks);button.disabled=!tasks.length;const batchTasks=state.tasks.filter(t=>t.batch_id===document.querySelector('#batch').value&&!t.title.includes('分发流程测试'));document.querySelector('#progress').textContent='本批 '+batchTasks.length+' 条 · 已核对 '+batchTasks.filter(t=>checked[t.id]).length+' 条 · 当前显示 '+tasks.length+' 条';document.querySelector('#confirm-next').disabled=!tasks.length;status.textContent=tasks.length?'选择内容后，先核对右侧视频与封面，再加载到视频号。':'没有匹配内容。清空搜索或切换到全部内容。';}
document.querySelector('#search').oninput=render;document.querySelector('#filter').onchange=render;

const assetURL=id=>'http://127.0.0.1:4318/api/assets/'+encodeURIComponent(id);
function renderCards(tasks){const list=document.querySelector('#cards'),scroll=list.scrollTop;list.replaceChildren();for(const t of tasks){const card=document.createElement('button');card.type='button';card.className='card'+(t.id===select.value?' selected':'');if(t.cover_id){const img=document.createElement('img');img.src=assetURL(t.cover_id);img.alt=t.title+'封面';card.append(img);}const text=document.createElement('span');text.textContent=orderLabel(t)+' '+t.title;const meta=document.createElement('small');meta.textContent=(t.publication_progress?.status==='published'?'✓ 已发布（人工确认） · ':checked[t.id]?'✓ 已人工核对 · ':'待核对 · ')+(t.asset_ids.length!==1?'视频未就绪':t.status==='unknown'?'先核对是否重复':t.scheduled?'计划 '+new Date(t.scheduled).toLocaleString('zh-CN'):t.status==='delivered'?'已存草稿':t.status==='review'?'审核中':'尚未记录发布结果')+' · '+t.account; text.append(meta);card.append(text);card.onclick=()=>{select.value=t.id;render();};list.append(card);}list.scrollTop=scroll;const preview=document.querySelector('#preview');preview.replaceChildren();const t=state.tasks.find(t=>t.id===select.value);document.querySelector('#selected-title').textContent=t?(state.batches?.find(b=>b.id===t.batch_id)?.name||'未归批次')+' · '+orderLabel(t)+' '+t.title:'没有匹配内容';if(!t){preview.textContent='没有匹配内容，请调整左侧搜索或批次。';return;}const heading=document.createElement('h2');heading.textContent=orderLabel(t)+' '+t.title;preview.append(heading);const media=document.createElement('div');media.className='media';const vf=document.createElement('figure'),video=document.createElement('video');video.controls=true;video.preload='metadata';if(t.cover_id)video.poster=assetURL(t.cover_id);if(t.asset_ids[0])video.src=assetURL(t.asset_ids[0]);const vc=document.createElement('figcaption');vc.textContent='视频预览';vf.append(video,vc);media.append(vf);const cf=document.createElement('figure'),cc=document.createElement('figcaption');cc.textContent='本条发布封面';if(t.cover_id){const image=document.createElement('img');image.src=assetURL(t.cover_id);image.alt=t.title+'封面';cf.append(image);}else cf.append('缺少封面');cf.append(cc);media.append(cf);preview.append(media);for(const [label,value] of [['发布文案',t.body],['话题',t.tags]]){const h=document.createElement('h3'),p=document.createElement('p');h.textContent=label;p.textContent=value||'未填写';preview.append(h,p);}const note=document.createElement('p');note.className='file-note';note.textContent=t.asset_ids.map(id=>state.assets.find(a=>a.id===id)?.name||'素材缺失').join('、');preview.append(note);localStorage.setItem('desk-selected-task',t.id);}


function taskOrder(t){if(Number.isInteger(t.sequence))return t.sequence;const a=state.assets.find(a=>a.id===t.asset_ids[0]);return Number(a?.name.match(/^(\d+)[-－]/)?.[1]||9999);}
function compareTasks(a,b){return taskOrder(a)-taskOrder(b)||a.title.localeCompare(b.title,"zh-CN");}
function orderLabel(t){const n=taskOrder(t);return n===9999?"未编序号":"第 "+String(n).padStart(2,"0")+" 条";}

document.querySelector('#expand').onclick=async()=>{try{const tab=targetTabId?await chrome.tabs.get(targetTabId):(await chrome.tabs.query({active:true,currentWindow:true}))[0];if(!tab?.url?.startsWith('https://channels.weixin.qq.com/'))throw Error('请从视频号页面打开此窗口');await chrome.windows.create({url:chrome.runtime.getURL('popup.html')+'?targetTab='+tab.id,type:'popup',width:1180,height:850});if(!targetTabId)window.close();}catch(e){status.textContent=e.message;}};

function renderBatches(){const el=document.querySelector('#batch'),saved=localStorage.getItem('desk-batch');const batches=state.batches||[];el.replaceChildren(...batches.filter(b=>state.tasks.some(t=>t.batch_id===b.id&&!t.title.includes('分发流程测试'))).map(b=>new Option(b.name+'（'+state.tasks.filter(t=>t.batch_id===b.id&&!t.title.includes('分发流程测试')).length+'条）',b.id)));if([...el.options].some(o=>o.value===saved))el.value=saved;}
document.querySelector('#batch').onchange=()=>{localStorage.setItem('desk-batch',document.querySelector('#batch').value);document.querySelector('#search').value='';select.value='';document.querySelector('#cards').scrollTop=0;document.querySelector('#start').value='';render();};

document.querySelector('#confirm-next').onclick=()=>{const t=state?.tasks.find(t=>t.id===select.value);if(!t)return;lastCheck={id:t.id,previous:checked[t.id]};document.querySelector('#undo').hidden=false;checked[t.id]=new Date().toISOString();localStorage.setItem('desk-checked-items',JSON.stringify(checked));const ordered=state.tasks.filter(x=>x.batch_id===t.batch_id&&!x.title.includes('分发流程测试')).sort(compareTasks);const next=ordered[ordered.findIndex(x=>x.id===t.id)+1];if(next){document.querySelector('#search').value='';document.querySelector('#filter').value='all';select.value=next.id;}render();status.textContent='已记录人工核对：'+orderLabel(t)+'。这不代表已保存草稿或发布。'+(next?'下一条：'+orderLabel(next)+' '+next.title:'本批已到最后一条。');};

document.querySelector('#settings-open').onclick=()=>document.querySelector('#settings').showModal();
document.querySelector('#settings-close').onclick=()=>document.querySelector('#settings').close();

document.querySelector('#undo').onclick=()=>{if(!lastCheck)return;const {id,previous}=lastCheck;if(previous)checked[id]=previous;else delete checked[id];localStorage.setItem('desk-checked-items',JSON.stringify(checked));document.querySelector('#search').value='';document.querySelector('#filter').value='all';select.value=id;lastCheck=null;document.querySelector('#undo').hidden=true;render();status.textContent='已撤销人工核对，回到刚才那条内容。';};
