/* Synthetic parser/state-machine tests. Does not open or operate a platform. */
const assert=require('node:assert/strict');
const {clickKind,resultKind,scheduleValue,validContext,createEngine}=require('../observer.js');
assert.equal(clickKind(' 发布 '),'submit_clicked');
assert.equal(clickKind('发布记录'),null);
assert.equal(clickKind('保存草稿'),'draft_clicked');
assert.equal(resultKind('发布成功'),'submit_clicked');
assert.equal(resultKind('已保存至草稿箱'),'draft_clicked');
for(const text of ['草稿箱','发布管理','发布','成功','上传成功','发布成功的内容将展示在这里','发布失败','保存成功'])assert.equal(resultKind(text),null,text);
assert.equal(scheduleValue('发布时间','2026-10-12 12:30'),'2026-10-12 12:30');
assert.equal(scheduleValue('视频标题','2026-10-12'), '');
assert.equal(scheduleValue('定时发表','明天'), '');
assert.equal(validContext({task_id:'abc',revision:1}),false,'selection alone cannot bind');
let time=1000,events=[],persisted;let seq=0;
const engine=createEngine({now:()=>time,id:()=>String(++seq),emit:e=>events.push(e),persist:s=>persisted=s});
const ctx={task_id:'abc',revision:2,binding_reason:'fill_started'};
assert.equal(engine.click('发表',true),false,'unbound click ignored');
assert.equal(engine.bind(ctx),true);
assert.equal(engine.result('发布成功'),false,'no submit intent');
assert.equal(engine.click('发表',false),false,'programmatic click ignored');
assert.equal(engine.click('发表',true,{observed_account:'测试账号',page_url:'https://channels.weixin.qq.com/platform/post/create'}),true);
assert.equal(engine.click('发表',true),false,'double click dedup');
assert.equal(engine.result('草稿保存成功'),false,'result must match intent');
assert.equal(engine.result('发布成功'),true);
assert.equal(engine.result('发布成功'),false,'result dedup');
assert.equal(events[1].event_kind,'result_observed');assert.equal(events[1].revision,2);
assert.equal(engine.schedule('定时发表','2026-10-12 12:30',true),true);
assert.equal(engine.schedule('定时发表','2026-10-12 12:30',true),false);
time+=2000;engine.click('保存草稿',true);time+=120001;
assert.equal(engine.result('草稿保存成功'),false,'stale result not attributed');
assert.equal(engine.bind({task_id:'replacement',revision:1}),false,'selecting another task cannot replace active binding');
assert.equal(engine.snapshot().binding.task_id,'abc');
engine.bind({...ctx,binding_reason:'manual_adoption'});time+=2000;engine.click('保存草稿',true);
const restored=createEngine({restore:persisted,now:()=>time,id:()=>String(++seq),emit:e=>events.push(e)});
assert.equal(restored.result('草稿保存成功'),true,'navigation preserves pending intent');
restored.clear();assert.equal(restored.click('发表',true),false,'new create route is unbound');
assert.equal(new Set(events.map(e=>e.event_id)).size,events.length);
assert.ok(events.every(e=>e.source==='session_observer'&&!('rawDOM' in e)));
console.log('observer synthetic tests passed');
// Result pages may lose their account header: retain the identity seen at click time.
let identityEvents=[];const identity=createEngine({emit:e=>identityEvents.push(e),now:()=>1000,id:()=>String(++seq)});
identity.bind(ctx);identity.click('发表',true,{observed_account:'账号甲'});identity.result('发布成功',{observed_account:''});
assert.equal(identityEvents[1].observed_account,'账号甲');
assert.match(identityEvents[1].result_text,/沿用提交时身份/);
identity.bind(ctx);identity.click('保存草稿',true,{observed_account:'账号甲'});identity.result('草稿保存成功',{observed_account:'账号乙'});
assert.equal(identityEvents[3].observed_account,'账号乙');
assert.match(identityEvents[3].result_text,/账号变化待核对/);
console.log('result identity continuity tests passed');
const {validTopURL}=require('../observer.js');
assert.equal(validTopURL('https://channels.weixin.qq.com/platform/post/create?token=hidden'),'https://channels.weixin.qq.com/platform/post/create');
assert.equal(validTopURL('https://channels.weixin.qq.com/platform/post/list'),'');
assert.equal(validTopURL('https://evil.test/platform/post/create'),'');
assert.equal(validTopURL('https://user:secret@channels.weixin.qq.com/platform/post/create'),'');
console.log('iframe top-page context validation tests passed');
